// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_qTkVn2UIU_X9OBi_uc7NEVQcNcg_tg',
    appId: '1:1032208386660:web:a01c5a1a2e127ca789ad71',
    messagingSenderId: '1032208386660',
    projectId: 'apiflutter-cc84a',
    authDomain: 'apiflutter-cc84a.firebaseapp.com',
    storageBucket: 'apiflutter-cc84a.firebasestorage.app',
    measurementId: 'G-BJFTCM3L47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRewQdQSY7acuVhLOFDLsa6mpNWNJehYo',
    appId: '1:1032208386660:android:4fb37c4e07139b3e89ad71',
    messagingSenderId: '1032208386660',
    projectId: 'apiflutter-cc84a',
    storageBucket: 'apiflutter-cc84a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpkwV4NmWd3gmqyB9TSLnBIFm_5V-EE2U',
    appId: '1:1032208386660:ios:da55d909e3a38aec89ad71',
    messagingSenderId: '1032208386660',
    projectId: 'apiflutter-cc84a',
    storageBucket: 'apiflutter-cc84a.firebasestorage.app',
    iosClientId: '1032208386660-0ifnsh9v5dkl321e7putvo5t90h4i6l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.statementHandle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpkwV4NmWd3gmqyB9TSLnBIFm_5V-EE2U',
    appId: '1:1032208386660:ios:da55d909e3a38aec89ad71',
    messagingSenderId: '1032208386660',
    projectId: 'apiflutter-cc84a',
    storageBucket: 'apiflutter-cc84a.firebasestorage.app',
    iosClientId: '1032208386660-0ifnsh9v5dkl321e7putvo5t90h4i6l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.statementHandle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4_qTkVn2UIU_X9OBi_uc7NEVQcNcg_tg',
    appId: '1:1032208386660:web:cb8f89e0f5a1162789ad71',
    messagingSenderId: '1032208386660',
    projectId: 'apiflutter-cc84a',
    authDomain: 'apiflutter-cc84a.firebaseapp.com',
    storageBucket: 'apiflutter-cc84a.firebasestorage.app',
    measurementId: 'G-4SJXC3PDLC',
  );
}
